# Generated by Django 6.0.5 on 2026-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service_number', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Ex-Serviceman', 'Ex-Serviceman'), ('Widow', 'Widow'), ('Dependent', 'Dependent'), ('Serving Personnel', 'Serving Personnel')], max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='enquiries/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
