# Generated by Django 6.0.5 on 2026-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('forms', 'Forms'), ('pension', 'Pension'), ('welfare', 'Welfare'), ('education', 'Education'), ('trust', 'Trust'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='downloads/')),
                ('description', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
